=== leandromelolm/ldd/LDD-Prova1-LeandroMelo/build/classes/ldd/Q1.xsd
<?xml version="1.0"?>
<!--XML Schema-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>                               
                <xs:element name="employee" type="tEmployee" maxOccurs="unbounded" />     
            </xs:sequence>
        </xs:complexType>
        <xs:key name="uniqueEmployeeNumber">
            <xs:selector xpath="employee"/>
            <xs:field xpath="@number"/>
        </xs:key>
        <xs:keyref name="ReportsToRef" refer="uniqueEmployeeNumber">
            <xs:selector xpath="employee"/>
            <xs:field xpath="reportsTo"/>
        </xs:keyref>
        <xs:unique name="codNumber">
            <xs:selector xpath="employee"/>
            <xs:field xpath="@number"/>
        </xs:unique>
    </xs:element>        
    <xs:complexType name="tEmployee">
        <xs:all>
            <xs:element name="lastName" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="firstName" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="extension" type="tExtension" minOccurs="1" maxOccurs="1"/>
            <xs:element name="email" type="tEmail"/>          
            <xs:element name="officeCode" type="xs:integer"/>
            <xs:element name="jobTitle" type="xs:string"/>
            <xs:element name="reportsTo" type="xs:integer"  minOccurs="0" maxOccurs="1"/>
        </xs:all>      
        <xs:attribute  name="number" type="xs:integer" /> 
    </xs:complexType>
    <xs:simpleType name="tExtension"> 
        <xs:restriction base="xs:string">
            <xs:minLength value="4" />
            <xs:maxLength value="5"/>
            <xs:pattern value="[x][0-9]*"/>                       
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tEmail"> 
        <xs:restriction base="xs:string">
            <xs:maxLength value="254"/>
            <xs:pattern value="[_\-a-zA-Z0-9\.\+]*[@][a-zA-Z0-9](\.?[\-a-zA-Z0-9])*"/>                       
        </xs:restriction>
    </xs:simpleType>   
            
    <!--    <xs:simpleType name= "tReportsTo">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="1002" />
            <xs:enumeration value="1056" />
            <xs:enumeration value="1102" />
            <xs:enumeration value="1143" />
            <xs:enumeration value="1088" />
            <xs:enumeration value="1621" />                                              
        </xs:restriction>
    </xs:simpleType>-->
</xs:schema>

=== leandromelolm/ldd/LDD-Prova1-LeandroMelo/build/classes/ldd/employees.xml
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q1.xsd">
    <!--        
        Validate XML Q1.xsd com XML Schema
        (atalho netbeans12.3 ALT + Shift + f9)
    -->
    <employee number="1002">
        <lastName>Murphy</lastName>
        <firstName>Diane</firstName>
        <extension>x5800</extension>
        <email>dmurphy@classicmodelcars.com</email>
        <officeCode>1</officeCode>
        <jobTitle>President</jobTitle>
    </employee>
    <employee number="1056">
        <lastName>Patterson</lastName>
        <firstName>Mary</firstName>
        <extension>x4611</extension>
        <email>mpatterso@classicmodelcars.com</email>
        <officeCode>1</officeCode>
        <reportsTo>1002</reportsTo>
        <jobTitle>VP Sales</jobTitle>
    </employee>
    <employee number="1076">
        <lastName>Firrelli</lastName>
        <firstName>Jeff</firstName>
        <extension>x9273</extension>
        <email>jfirrelli@classicmodelcars.com</email>
        <officeCode>1</officeCode>
        <reportsTo>1002</reportsTo>
        <jobTitle>VP Marketing</jobTitle>
    </employee>
    <employee number="1088">
        <lastName>Patterson</lastName>
        <firstName>William</firstName>
        <extension>x4871</extension>
        <email>wpatterson@classicmodelcars.com</email>
        <officeCode>6</officeCode>
        <reportsTo>1056</reportsTo>
        <jobTitle>Sales Manager (APAC)</jobTitle>
    </employee>
    <employee number="1102">
        <lastName>Bondur</lastName>
        <firstName>Gerard</firstName>
        <extension>x5408</extension>
        <email>gbondur@classicmodelcars.com</email>
        <officeCode>4</officeCode>
        <reportsTo>1056</reportsTo>
        <jobTitle>Sale Manager (EMEA)</jobTitle>
    </employee>
    <employee number="1143">
        <lastName>Bow</lastName>
        <firstName>Anthony</firstName>
        <extension>x5428</extension>
        <email>abow@classicmodelcars.com</email>
        <officeCode>1</officeCode>
        <reportsTo>1056</reportsTo>
        <jobTitle>Sales Manager (NA)</jobTitle>
    </employee>
    <employee number="1165">
        <lastName>Jennings</lastName>
        <firstName>Leslie</firstName>
        <extension>x3291</extension>
        <email>ljennings@classicmodelcars.com</email>
        <officeCode>1</officeCode>
        <reportsTo>1143</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1166">
        <lastName>Thompson</lastName>
        <firstName>Leslie</firstName>
        <extension>x4065</extension>
        <email>lthompson@classicmodelcars.com</email>
        <officeCode>1</officeCode>
        <reportsTo>1143</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1188">
        <lastName>Firrelli</lastName>
        <firstName>Julie</firstName>
        <extension>x2173</extension>
        <email>jfirrelli@classicmodelcars.com</email>
        <officeCode>2</officeCode>
        <reportsTo>1143</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1216">
        <lastName>Patterson</lastName>
        <firstName>Steve</firstName>
        <extension>x4334</extension>
        <email>spatterson@classicmodelcars.com</email>
        <officeCode>2</officeCode>
        <reportsTo>1143</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1286">
        <lastName>Tseng</lastName>
        <firstName>Foon Yue</firstName>
        <extension>x2248</extension>
        <email>ftseng@classicmodelcars.com</email>
        <officeCode>3</officeCode>
        <reportsTo>1143</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1323">
        <lastName>Vanauf</lastName>
        <firstName>George</firstName>
        <extension>x4102</extension>
        <email>gvanauf@classicmodelcars.com</email>
        <officeCode>3</officeCode>
        <reportsTo>1143</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1337">
        <lastName>Bondur</lastName>
        <firstName>Loui</firstName>
        <extension>x6493</extension>
        <email>lbondur@classicmodelcars.com</email>
        <officeCode>4</officeCode>
        <reportsTo>1102</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1370">
        <lastName>Hernandez</lastName>
        <firstName>Gerard</firstName>
        <extension>x2028</extension>
        <email>ghernande@classicmodelcars.com</email>
        <officeCode>4</officeCode>
        <reportsTo>1102</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1401">
        <lastName>Castillo</lastName>
        <firstName>Pamela</firstName>
        <extension>x2759</extension>
        <email>pcastillo@classicmodelcars.com</email>
        <officeCode>4</officeCode>
        <reportsTo>1102</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1501">
        <lastName>Bott</lastName>
        <firstName>Larry</firstName>
        <extension>x2311</extension>
        <email>lbott@classicmodelcars.com</email>
        <officeCode>7</officeCode>
        <reportsTo>1102</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1504">
        <lastName>Jones</lastName>
        <firstName>Barry</firstName>
        <extension>x102</extension>
        <email>bjones@classicmodelcars.com</email>
        <officeCode>7</officeCode>
        <reportsTo>1102</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1611">
        <lastName>Fixter</lastName>
        <firstName>Andy</firstName>
        <extension>x101</extension>
        <email>afixter@classicmodelcars.com</email>
        <officeCode>6</officeCode>
        <reportsTo>1088</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1612">
        <lastName>Marsh</lastName>
        <firstName>Peter</firstName>
        <extension>x102</extension>
        <email>pmarsh@classicmodelcars.com</email>
        <officeCode>6</officeCode>
        <reportsTo>1088</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1619">
        <lastName>King</lastName>
        <firstName>Tom</firstName>
        <extension>x103</extension>
        <email>tking@classicmodelcars.com</email>
        <officeCode>6</officeCode>
        <reportsTo>1088</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1621">
        <lastName>Nishi</lastName>
        <firstName>Mami</firstName>
        <extension>x101</extension>
        <email>mnishi@classicmodelcars.com</email>
        <officeCode>5</officeCode>
        <reportsTo>1056</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1625">
        <lastName>Kato</lastName>
        <firstName>Yoshimi</firstName>
        <extension>x102</extension>
        <email>ykato@classicmodelcars.com</email>
        <officeCode>5</officeCode>
        <reportsTo>1621</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
    <employee number="1702">
        <lastName>Gerard</lastName>
        <firstName>Martin</firstName>
        <extension>x2312</extension>
        <email>mgerard@classicmodelcars.com</email>
        <officeCode>4</officeCode>
        <reportsTo>1102</reportsTo>
        <jobTitle>Sales Rep</jobTitle>
    </employee>
</employees>
